# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a2626bf66b88cf2163c8eba263198c8484b9992fc699cee38a4e140005c9890a2128ae5bb47b2467936ce5834eb7488d9250bf2a96c3a0a09f0ffb5e46d676d

test:
  secret_key_base: 659045470210684e0244af46afe80432e893b0ba56e1a5da15b5f4bc4f96b8194a853406d67a20e49c3430ab86234d1dfc9d8e5c22d43036f5cd9df30766e8a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
